package com.robothy.s3.core.assertions;

import com.robothy.s3.core.exception.LocalS3InvalidArgumentException;
import com.robothy.s3.core.exception.VersionedObjectNotExistException;
import com.robothy.s3.core.model.internal.ObjectMetadata;
import com.robothy.s3.core.model.internal.VersionedObjectMetadata;
import java.util.Objects;
import java.util.Optional;

public class VersionedObjectAssertions {

  /**
   * Assert that a version ID of a request is one that LocalS3 could have given, i.e. {@code null} or a number, which
   * the IDs it generates are; a negative one was generated by an overflowed generator. Like Amazon S3, a version ID
   * that is malformed is an invalid argument rather than a version that doesn't exist.
   *
   * @param versionId the version ID of the request; {@code null} if it names none.
   * @throws LocalS3InvalidArgumentException if the version ID is malformed.
   */
  public static void assertVersionIdIsValid(String versionId) {
    if (Objects.isNull(versionId) || ObjectMetadata.NULL_VERSION.equals(versionId)) {
      return;
    }
    int start = versionId.startsWith("-") ? 1 : 0;
    boolean valid = versionId.length() > start && versionId.length() <= start + 19;
    for (int i = start; valid && i < versionId.length(); i++) {
      char c = versionId.charAt(i);
      valid = c >= '0' && c <= '9';
    }
    if (!valid) {
      throw invalidVersionId(versionId);
    }
  }

  /**
   * The error of a version ID that names no version a request could address, e.g. a malformed one, or one other than
   * {@code "null"} for a bucket that was never versioned, whose objects have no other version; the message is the one of
   * Amazon S3.
   *
   * @param versionId the version ID of the request.
   * @return the {@code InvalidArgument} error to throw.
   */
  public static LocalS3InvalidArgumentException invalidVersionId(String versionId) {
    return new LocalS3InvalidArgumentException("versionId", versionId, "Invalid version id specified");
  }

  /**
   * Find the version that a version ID other than {@code "null"} names. The version ID that the null version is held by
   * inside LocalS3 is never answered to a client, which knows the version as {@code "null"} only, so it names no
   * version.
   *
   * @param objectMetadata object metadata.
   * @param versionId the version ID; neither {@code null} nor {@code "null"}.
   * @return the version; empty if the object holds no such version.
   * @throws LocalS3InvalidArgumentException if the version ID is malformed.
   */
  public static Optional<VersionedObjectMetadata> findVersionedObject(ObjectMetadata objectMetadata, String versionId) {
    assertVersionIdIsValid(versionId);
    if (objectMetadata.getVirtualVersion().map(versionId::equals).orElse(false)) {
      return Optional.empty();
    }
    return objectMetadata.getVersionedObjectMetadata(versionId);
  }

  /**
   * Asset that the specified object and version is exist in the bucket.
   * @param objectMetadata object metadata.
   * @param version object version; neither {@code null} nor {@code "null"}.
   * @return the {@linkplain VersionedObjectMetadata} of the specified version.
   * @throws LocalS3InvalidArgumentException if the version ID is malformed.
   * @throws VersionedObjectNotExistException if the object holds no such version.
   */
  public static VersionedObjectMetadata assertVersionedObjectExist(ObjectMetadata objectMetadata, String version) {
    return findVersionedObject(objectMetadata, version)
        .orElseThrow(() -> new VersionedObjectNotExistException(version));
  }

  /**
   * Assert that the specified {@linkplain ObjectMetadata} has virtual version.
   *
   * @param objectMetadata the object metadata.
   * @return the {@linkplain VersionedObjectMetadata} instance.
   */
  public static VersionedObjectMetadata assertVirtualVersionExist(ObjectMetadata objectMetadata) {
    return objectMetadata.getVirtualVersion().map(virtualVersion -> objectMetadata.getVersionedObjectMap().get(virtualVersion))
        .orElseThrow(() -> new VersionedObjectNotExistException(ObjectMetadata.NULL_VERSION));
  }

}
