services:
  local-s3-java:
    image: luofuxiang/local-s3:2.5-SNAPSHOT
    ports:
      - "29090:29090"
  local-s3-native:
    image: luofuxiang/local-s3:native-2.5-SNAPSHOT
    ports:
      - "39090:29090"