package com.robothy.s3.core.service.loader;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import com.robothy.s3.core.model.answers.ListObjectVersionsAns;
import com.robothy.s3.core.model.answers.PutObjectAns;
import com.robothy.s3.core.model.internal.BucketMetadata;
import com.robothy.s3.core.model.internal.ObjectMetadata;
import com.robothy.s3.core.model.internal.VersionedObjectMetadata;
import com.robothy.s3.core.model.request.PutObjectOptions;
import com.robothy.s3.core.service.ObjectService;
import com.robothy.s3.core.service.manager.LocalS3Manager;
import com.robothy.s3.core.storage.FileSystemBucketMetadataStore;
import com.robothy.s3.datatypes.response.ObjectVersion;
import java.io.ByteArrayInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Test;

class DefaultFileSystemS3MetadataLoaderTest {

  /**
   * A version ID generated by a LocalS3 that computed the timestamp against an epoch expressed in
   * seconds. Such IDs are far larger than the ones generated now, so a version added after loading
   * them has to keep following them, or it wouldn't be the latest version of the object.
   */
  private static final long LEGACY_VERSION_ID = 7496428310230990849L;

  @Test
  void versionAddedToALoadedObjectIsTheLatestOne() throws Exception {
    Path dataPath = Files.createTempDirectory("local-s3");
    String bucketName = "my-bucket";
    String key = "key";
    persistBucketWithLegacyVersion(dataPath, bucketName, key);

    ObjectService objectService = LocalS3Manager.createFileSystemS3Manager(dataPath).objectService();
    PutObjectAns putObjectAns = objectService.putObject(bucketName, key, PutObjectOptions.builder()
        .contentType("plain/text")
        .content(new ByteArrayInputStream("Robothy".getBytes()))
        .size(7)
        .build());

    assertTrue(Long.parseLong(putObjectAns.getVersionId()) > LEGACY_VERSION_ID,
        "The new version " + putObjectAns.getVersionId() + " doesn't follow the loaded " + LEGACY_VERSION_ID);

    ListObjectVersionsAns versions = objectService.listObjectVersions(bucketName, null, null, 10, null, null);
    assertEquals(2, versions.getVersions().size());
    ObjectVersion latest = (ObjectVersion) versions.getVersions().get(0);
    assertEquals(putObjectAns.getVersionId(), latest.getVersionId());
    assertTrue(latest.isLatest());

    FileUtils.deleteDirectory(dataPath.toFile());
  }

  private void persistBucketWithLegacyVersion(Path dataPath, String bucketName, String key) {
    BucketMetadata bucketMetadata = new BucketMetadata();
    bucketMetadata.setBucketName(bucketName);
    bucketMetadata.setCreationDate(System.currentTimeMillis());
    bucketMetadata.setVersioningEnabled(true);

    VersionedObjectMetadata versionedObjectMetadata = new VersionedObjectMetadata();
    versionedObjectMetadata.setCreationDate(System.currentTimeMillis());
    versionedObjectMetadata.setFileId(LEGACY_VERSION_ID);
    versionedObjectMetadata.setSize(7);
    versionedObjectMetadata.setEtag("etag");
    bucketMetadata.putObjectMetadata(key,
        new ObjectMetadata(String.valueOf(LEGACY_VERSION_ID), versionedObjectMetadata));

    FileSystemBucketMetadataStore.create(dataPath).store(bucketName, bucketMetadata);
  }

}
