package com.robothy.s3.core.service.loader;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import com.robothy.s3.core.model.answers.ListObjectVersionsAns;
import com.robothy.s3.core.model.answers.PutObjectAns;
import com.robothy.s3.core.model.internal.BucketMetadata;
import com.robothy.s3.core.model.internal.ObjectMetadata;
import com.robothy.s3.core.model.internal.VersionedObjectMetadata;
import com.robothy.s3.core.model.request.PutObjectOptions;
import com.robothy.s3.core.service.ObjectService;
import com.robothy.s3.core.service.manager.LocalS3Manager;
import com.robothy.s3.core.storage.LocalS3Store;
import com.robothy.s3.core.storage.MVStoreBucketMetadataStore;
import com.robothy.s3.core.util.JsonUtils;
import com.robothy.s3.datatypes.response.ObjectVersion;
import java.io.ByteArrayInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import com.robothy.s3.core.TestFiles;
import org.junit.jupiter.api.Test;

class DefaultFileSystemS3MetadataLoaderTest {

  /**
   * A version ID generated by a LocalS3 that computed the timestamp against an epoch expressed in
   * seconds. Such IDs are far larger than the ones generated now, so a version added after loading
   * them has to keep following them, or it wouldn't be the latest version of the object.
   */
  private static final long LEGACY_VERSION_ID = 7496428310230990849L;

  @Test
  void versionAddedToALoadedObjectIsTheLatestOne() throws Exception {
    Path dataPath = Files.createTempDirectory("local-s3");
    String bucketName = "my-bucket";
    String key = "key";
    persistBucketWithLegacyVersion(dataPath, bucketName, key);

    ObjectService objectService = LocalS3Manager.createFileSystemS3Manager(dataPath).objectService();
    PutObjectAns putObjectAns = objectService.putObject(bucketName, key, PutObjectOptions.builder()
        .contentType("plain/text")
        .content(new ByteArrayInputStream("Robothy".getBytes()))
        .size(7)
        .build());

    assertTrue(Long.parseLong(putObjectAns.getVersionId()) > LEGACY_VERSION_ID,
        "The new version " + putObjectAns.getVersionId() + " doesn't follow the loaded " + LEGACY_VERSION_ID);

    ListObjectVersionsAns versions = objectService.listObjectVersions(bucketName, null, null, 10, null, null);
    assertEquals(2, versions.getVersions().size());
    ObjectVersion latest = (ObjectVersion) versions.getVersions().get(0);
    assertEquals(putObjectAns.getVersionId(), latest.getVersionId());
    assertTrue(latest.isLatest());

    TestFiles.deleteDirectory(dataPath);
  }

  /**
   * A bucket records the greatest ID it references as it is written, which is what the generator is normally seeded
   * from. A data directory written before that was recorded holds no such number, so the IDs in use are found by
   * reading the objects of the bucket once, and a version added after loading it still follows them.
   */
  @Test
  void seedsTheGeneratorByReadingABucketThatRecordsNoGreatestId() throws Exception {
    Path dataPath = Files.createTempDirectory("local-s3");
    String bucketName = "legacy-bucket";
    String key = "key";
    persistBucketWithLegacyVersion(dataPath, bucketName, key);
    stripRecordedMaxId(dataPath, bucketName);

    ObjectService objectService = LocalS3Manager.createFileSystemS3Manager(dataPath).objectService();
    PutObjectAns putObjectAns = objectService.putObject(bucketName, key, PutObjectOptions.builder()
        .contentType("plain/text")
        .content(new ByteArrayInputStream("Robothy".getBytes()))
        .size(7)
        .build());

    assertTrue(Long.parseLong(putObjectAns.getVersionId()) > LEGACY_VERSION_ID,
        "The new version " + putObjectAns.getVersionId() + " doesn't follow the loaded " + LEGACY_VERSION_ID);

    TestFiles.deleteDirectory(dataPath);
  }

  /**
   * Leave a bucket the way a LocalS3 that didn't record the greatest ID left it: the objects are there, the number
   * that describes them isn't.
   */
  private void stripRecordedMaxId(Path dataPath, String bucketName) {
    try (LocalS3Store store = LocalS3Store.persistent(dataPath)) {
      BucketMetadata bucketMetadata = MVStoreBucketMetadataStore.create(store).fetch(bucketName);
      assertNotNull(bucketMetadata.getMaxId(), "The bucket was written with the greatest ID it references.");
      bucketMetadata.setMaxId(null);
      store.store().openMap("buckets").put(bucketName, JsonUtils.toJson(bucketMetadata));
      store.store().commit();
    }
  }

  private void persistBucketWithLegacyVersion(Path dataPath, String bucketName, String key) {
    BucketMetadata bucketMetadata = new BucketMetadata();
    bucketMetadata.setBucketName(bucketName);
    bucketMetadata.setCreationDate(System.currentTimeMillis());
    bucketMetadata.setVersioningEnabled(true);

    VersionedObjectMetadata versionedObjectMetadata = new VersionedObjectMetadata();
    versionedObjectMetadata.setCreationDate(System.currentTimeMillis());
    versionedObjectMetadata.setFileId(LEGACY_VERSION_ID);
    versionedObjectMetadata.setSize(7);
    versionedObjectMetadata.setEtag("etag");
    bucketMetadata.putObjectMetadata(key,
        new ObjectMetadata(String.valueOf(LEGACY_VERSION_ID), versionedObjectMetadata));

    try (LocalS3Store store = LocalS3Store.persistent(dataPath)) {
      MVStoreBucketMetadataStore.create(store).store(bucketName, bucketMetadata);
    }
  }

}
